### ISSUE TITLE
hikbot suggest

### ISSUE THREAD

**Issue by myuid** [sarjsheff/hikbot#1]
Great job.Hikbot can only be used for tier 1 defense. If tier 1 defense is occupied, then you need to use tier 2 defense. I suggest using the secondary protection functions NET_DVR_SetDVRMessageCallBack_V30 and NET_DVR_SetupAlarmChan_V41 instead of NET_DVR_SetDVRMessCallBack and NET_DVR_StartListen Better.

**Comment by sarjsheff** [comment]
I don't understand what these "defense tiers" are, but I made some changes. Hope this will be helpful.

Maybe you know how to get a snapshot with an event without calling NET_DVR_CaptureJPEGPicture?
